runtime: php82
entrypoint: serve public/index.php

env_variables:
  APP_ENV: production
  APP_DEBUG: false
  APP_KEY: __APP_KEY__
  LOG_CHANNEL: stderr
  CACHE_DRIVER: file
  SESSION_DRIVER: file
  STORAGE_DIR: /tmp
