steps:
  # Step 1: Install PHP dependencies
  - name: "gcr.io/cloud-builders/composer"
    args: ["install", "--no-dev", "--prefer-dist"]

  # Step 2: Install Node dependencies
  - name: "node:18"
    entrypoint: "npm"
    args: ["install"]

  # Step 3: Build frontend (Vite)
  - name: "node:18"
    entrypoint: "npm"
    args: ["run", "build"]

  # Step 4: Run `php artisan storage:link`
  - name: "php:8.2"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        apt-get update && apt-get install -y unzip git zip libzip-dev
        curl -sS https://getcomposer.org/installer | php
        php composer.phar install --no-dev --prefer-dist
        php artisan storage:link

  # Step 5: Inject `APP_KEY` into `app.yaml`
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        sed "s|__APP_KEY__|$_APP_KEY|" app.yaml.template > app.yaml

  # Step 6: Deploy to App Engine
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args: ["app", "deploy", "app.yaml", "--quiet"]

substitutions:
  _APP_KEY: ""
