steps:
  # Step 1: Install PHP, Composer, ekstensi & Laravel deps
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:latest"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        apt-get update
        apt-get install -y \
          php \
          php-mbstring \
          php-xml \
          php-zip \
          php-sqlite3 \
          unzip \
          git \
          curl

        curl -sS https://getcomposer.org/installer | php
        php composer.phar install --no-dev --prefer-dist --no-interaction
        php artisan storage:link

  # Step 2: Install Node dependencies
  - name: "node:18"
    entrypoint: "npm"
    args: ["install"]

  # Step 3: Build frontend (Vite)
  - name: "node:18"
    entrypoint: "npm"
    args: ["run", "build"]

  # Step 4: Inject APP_KEY ke app.yaml
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        sed "s|__APP_KEY__|$_APP_KEY|" app.yaml.template > app.yaml

  # Step 5: Deploy ke App Engine
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args: ["app", "deploy", "app.yaml", "--quiet"]

substitutions:
  _APP_KEY: ""

options:
  logging: CLOUD_LOGGING_ONLY
